# &default alias removed to resolve psych gem error

development:
  adapter: mysql2
  encoding: utf8mb4
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  database: tapas
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8mb4
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  database: tapas
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8mb4
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  database: tapas
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /tmp/mysql.sock
