development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://tomcat.archimedes.digital/fcrepo-webapp-5.1.0
staging:
  user: fedoraAdmin
  password: <%= ENV['STAGING_FEDORA_PASSWORD'] %>
  url: http://127.0.0.1:8080/fedora
production:
  user: fedoraAdmin
  password: <%= ENV['PRODUCTION_FEDORA_PASSWORD'] %>
  url: http://127.0.0.1:8080/fedora
test: &TEST
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
cucumber:
  <<: *TEST
